-- ============================================================
-- 军师 - 用户反馈收集（v20260806）
--
-- 背景：指导页 guide.html 尾部"联系我们"按钮 → 用户提交反馈，
--   管理员在 admin 后台"反馈管理"tab 查看/标记处理。
--
-- 表：feedback（content 必填 ≤2000 字；contact 可选 ≤100 字）
-- RPC：
--   submit_feedback(p_content, p_contact)  —— 任何人可提交（anon 也可）
--   admin_feedback_list()                  —— 管理员读全部（new 在前）
--   admin_feedback_mark(p_id, p_status)    —— 管理员改状态 new/done
--
-- 鉴权：admin_* 函数 SECURITY DEFINER + 校验 profiles.is_admin；
--       submit_feedback 无需鉴权（面向所有访客，content 做长度/空值校验）。
-- 执行位置：Supabase Dashboard → SQL Editor（或管理 API database/query）
-- ============================================================

-- 1. 反馈表
CREATE TABLE IF NOT EXISTS public.feedback (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    text NOT NULL,
    contact    text NOT NULL DEFAULT '',
    status     text NOT NULL DEFAULT 'new',   -- new / done
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 表级授权：仅 service_role 可直查/改（admin 前端走 RPC，规避 RLS 直查）
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback TO service_role;

-- 2. 提交反馈（公开：anon / authenticated 都能调）
CREATE OR REPLACE FUNCTION public.submit_feedback(p_content text, p_contact text DEFAULT '')
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_content text := btrim(coalesce(p_content, ''));
    v_contact text := btrim(coalesce(p_contact, ''));
BEGIN
    IF v_content = '' THEN
        RETURN jsonb_build_object('success', false, 'message', '反馈内容不能为空');
    END IF;
    IF length(v_content) > 2000 THEN
        RETURN jsonb_build_object('success', false, 'message', '内容过长，请精简到 2000 字以内');
    END IF;

    INSERT INTO public.feedback (content, contact)
    VALUES (left(v_content, 2000), left(v_contact, 100));

    RETURN jsonb_build_object('success', true, 'message', '已收到，我们会尽快回复你');
END;
$$;

-- 3. 管理员：读取全部反馈（new 在前）
CREATE OR REPLACE FUNCTION public.admin_feedback_list()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_has_admin boolean;
    v_list jsonb;
BEGIN
    SELECT is_admin INTO v_has_admin FROM public.profiles WHERE id = auth.uid();
    IF NOT coalesce(v_has_admin, false) THEN
        RETURN jsonb_build_object('error', 'forbidden');
    END IF;

    SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY t.created_at DESC), '[]'::jsonb) INTO v_list
    FROM (
        SELECT id, content, contact, status, created_at
        FROM public.feedback
    ) t;

    RETURN jsonb_build_object('list', v_list);
END;
$$;

-- 4. 管理员：标记处理状态（new ↔ done）
CREATE OR REPLACE FUNCTION public.admin_feedback_mark(p_id bigint, p_status text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_has_admin boolean;
    v_status text := lower(btrim(coalesce(p_status, 'new')));
BEGIN
    SELECT is_admin INTO v_has_admin FROM public.profiles WHERE id = auth.uid();
    IF NOT coalesce(v_has_admin, false) THEN
        RETURN jsonb_build_object('error', 'forbidden');
    END IF;
    IF v_status NOT IN ('new', 'done') THEN
        RETURN jsonb_build_object('error', 'invalid_status');
    END IF;

    UPDATE public.feedback SET status = v_status WHERE id = p_id;
    RETURN jsonb_build_object('success', true);
END;
$$;

-- 授权
GRANT EXECUTE ON FUNCTION public.submit_feedback(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_feedback_list() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_feedback_mark(bigint, text) TO authenticated;
