// v101 恢复验证：确认 thinking_mode=off、无思考预算、回复正常
const PAT = process.env.SBP_PAT;
const REF = 'opzvvgixlfbfpdlsorbi';
const BASE = `https://${REF}.supabase.co`;
const API = `https://api.supabase.com/v1/projects/${REF}`;
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126.0 Safari/537.36';
const kr = await fetch(`${API}/api-keys`, { headers: { Authorization: `Bearer ${PAT}` } });
const keys = await kr.json();
const sr = keys.find(k => k.name === 'service_role' || k.role === 'service_role');
const JWT = sr.api_key || sr.key;
const email = `v101_${Date.now()}@jssl.local`;
const pwd = 'E2eTest!2026';
const u = await fetch(`${BASE}/auth/v1/admin/users`, { method: 'POST', headers: { Authorization: `Bearer ${JWT}`, apikey: JWT, 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: pwd, email_confirm: true }) });
const uid = (await u.json())?.id;
await fetch(`${BASE}/rest/v1/rpc/register_account`, { method: 'POST', headers: { Authorization: `Bearer ${JWT}`, apikey: JWT, 'Content-Type': 'application/json' }, body: JSON.stringify({ p_account_user_id: uid, p_account_name: 'v101验证', p_device_id: 'v101_dbg_000001' }) });
await fetch(`${BASE}/rest/v1/rpc/login_account`, { method: 'POST', headers: { Authorization: `Bearer ${JWT}`, apikey: JWT, 'Content-Type': 'application/json' }, body: JSON.stringify({ p_account_user_id: uid, p_session_id: 'v101_session_001' }) });
const tok = await fetch(`${BASE}/auth/v1/token?grant_type=password`, { method: 'POST', headers: { apikey: JWT, 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: pwd }) });
const accountToken = (await tok.json())?.access_token;
const sid = await fetch(`${BASE}/rest/v1/chat_sessions`, { method: 'POST', headers: { Authorization: `Bearer ${accountToken}`, apikey: JWT, 'Content-Type': 'application/json', Prefer: 'return=representation' }, body: JSON.stringify({ user_id: uid, note: 'v101验证', friend_name: '测试' }) });
const sessionIdDb = (await sid.json())?.[0]?.id;
const r = await fetch(`${BASE}/functions/v1/ima-proxy`, { method: 'POST', headers: { Authorization: `Bearer ${accountToken}`, apikey: JWT, 'Content-Type': 'application/json', 'X-Identity-Type': 'account', 'X-Session-Id': 'v101_session_001' }, body: JSON.stringify({ query: '她说今天好无聊呀，其实我是想多了解你一点', history: [], session_id: sessionIdDb }) });
const d = await r.json();
const dbg = d._debug || {};
console.log('reply:', d.reply);
console.log('thinking_mode:', dbg.thinking_mode);
console.log('llm_reasoning:', JSON.stringify(dbg.llm_reasoning));
console.log('tactic:', dbg.tactic_category, '/', dbg.tactic_phase);
const usage = dbg.llm_usage || [];
for (const u of usage) console.log(`  ${u.stage}: prompt=${u.prompt_tokens} completion=${u.completion_tokens} total=${u.total_tokens}`);
await fetch(`${API}/database/query`, { method: 'POST', headers: { Authorization: `Bearer ${PAT}`, 'Content-Type': 'application/json', 'User-Agent': UA }, body: JSON.stringify({ query: `delete from public.chat_sessions where user_id = '${uid}'` }) });
await fetch(`${API}/database/query`, { method: 'POST', headers: { Authorization: `Bearer ${PAT}`, 'Content-Type': 'application/json', 'User-Agent': UA }, body: JSON.stringify({ query: `delete from public.accounts where id = '${uid}'` }) });
await fetch(`${BASE}/auth/v1/admin/users/${uid}`, { method: 'DELETE', headers: { Authorization: `Bearer ${JWT}`, apikey: JWT } });
console.log('临时账号已清理');
